### ISSUE TITLE
PSR-6 Compatibility

### ISSUE THREAD

**Issue by ComMouse** [dyweb/redis-cache#3]
It is necessary to make this lib compatible with PSR-6 Caching Interface to ensure compatibility with other libraries.

The details of the PSR-6 standard can be found here:

http://www.php-fig.org/psr/psr-6/

@at15 @arrowrowe @xsfour @LukeXuan

**Comment by at15** [comment]
0.0 so? need someone handle this?

**Comment by ComMouse** [comment]
yeap

**Comment by at15** [comment]
somehow, I felt I should leave this burden to the young man, I am too old to do this, and should spend more time on looking for gf \w/

**Comment by ComMouse** [comment]
@Bluemit Would you please finish this task? thx.

**Comment by at15** [comment]
some libraries that could be used for reference 
- https://github.com/tedious/Stash
- https://github.com/PHPSocialNetwork/phpfastcache
- https://github.com/bernardphp/bernard/tree/master/src/Driver

**Comment by ComMouse** [comment]
Since this PSR is of much conflict, we just need to make it work at present without considering its performance with such a complex interface... The current version might work now...

**Comment by at15** [comment]
....sad
