### ISSUE TITLE
Release in packagist

### ISSUE THREAD

**Issue by ComMouse** [dyweb/redis-cache#4]
As the basic development is finished, it's time to publish it on packagist and use it in tongqu. Someone need to register a packagist account and release this lib...

@at15 @Bluemit

**Comment by at15** [comment]
@ComMouse leave it to you /w\

**Comment by ComMouse** [comment]
@at15 https://packagist.org/search/?q=dyweb The account has been already taken

**Comment by at15** [comment]
@ComMouse yeah, I got the account.

**Comment by at15** [comment]
- https://packagist.org/packages/dyweb/redis-cache The webhook should be working now

**Comment by ComMouse** [comment]
Thx. =w=
